In [1]:
import pandas as pd

df_new_spiral = pd.read_csv("NewSpiral.csv")
df_new_meader = pd.read_csv("NewMeander.csv")

df_new_spiral.head()

,_ID_EXAM,IMAGE_NAME,ID_PATIENT,CLASS_TYPE,GENDER,RIGH/LEFT-HANDED,AGE,RMS,MAX_BETWEEN_ET_HT,MIN_BETWEEN_ET_HT,STD_DEVIATION_ET_HT,MRT,MAX_HT,MIN_HT,STD_HT,CHANGES_FROM_NEGATIVE_TO_POSITIVE_BETWEEN_ET_HT
0,H1,sp1-H1.jpg,59,1,M,R,58,14900.772670,13207.241210,40856.39894,0.087041,56.978320,192.737170,0.026662,4394.307090,0.120773
1,H2,sp1-H2.jpg,76,1,M,R,60,6076.106534,9440.754502,36137.73814,0.065872,39.597318,169.753376,0.266595,2031.447046,0.172414
2,H3,sp1-H3.jpg,301,1,F,R,56,12220.462340,12247.263300,39871.73569,0.000000,46.183810,192.536776,0.007857,3843.754479,0.123894
3,H4,sp1-H4.jpg,102,1,M,R,24,4810.072073,4904.029458,32262.38975,0.044374,31.485790,200.401229,0.114530,1586.941716,0.162011
4,H5,sp1-H5.jpg,305,1,M,R,79,5458.875925,5911.591981,31795.46792,0.040906,47.231442,134.897863,0.026703,2251.866128,0.202899

In [2]:
df_spiral = pd.read_csv("Spiral_HandPD.csv")
df_meader = pd.read_csv("Meander_HandPD.csv")

df_spiral.head()

,368,2,9,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,0,1,1,3521.258301,6247.052734,30801.992188,0.014133,26.785328,176.600113,0.002130,1781.795898,0.250000
1,1,2,1,4098.876465,6032.535156,34369.703125,0.022838,26.529615,168.352737,0.084960,1443.217529,0.273585
2,2,3,1,3854.601807,6453.114746,34709.445312,0.000251,23.670755,180.898300,0.009303,1621.750000,0.256329
3,3,4,1,4069.221924,6844.231445,32181.263672,0.000168,23.456329,179.116043,0.021419,1454.390137,0.249221
4,4,5,1,4104.271973,6949.925293,36444.953125,0.004731,22.488258,188.256210,0.000000,1553.536499,0.214511